version: '3.8'

networks:
  coolify:
    external: true

services:
  proxy:
    image: nginx:latest
    container_name: proxy

    extra_hosts:
      - host.docker.internal:host-gateway

    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/conf.d/coolify.conf:/etc/nginx/conf.d/coolify.conf
      - ./etc/nginx/conf.d/ollama.conf:/etc/nginx/conf.d/ollama.conf
      - ./etc/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
      - ./etc/nginx/ssl:/etc/nginx/ssl

    networks:
      - coolify

    ports:
      - '80:80'
      - '443:443'

    restart: always

    logging:
      driver: json-file
      options:
        tag: '{{.Name}}'
